'use client';

import { useQuery } from '@tanstack/react-query';
import { workspaceAPI, analyticsAPI, milestoneAPI } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { FileText, Copy, Download, CheckCircle2, Sparkles } from 'lucide-react';
import { useState } from 'react';

export function PitchGenerator({ workspaceId }: { workspaceId: string }) {
  const [copied, setCopied] = useState(false);

  const { data: workspace } = useQuery({
    queryKey: ['workspace', workspaceId],
    queryFn: async () => {
      const response = await workspaceAPI.getById(workspaceId);
      return response.data;
    },
  });

  const { data: analytics } = useQuery({
    queryKey: ['analytics', workspaceId],
    queryFn: async () => {
      const response = await analyticsAPI.getWorkspaceAnalytics(workspaceId);
      return response.data;
    },
  });

  const { data: milestones } = useQuery({
    queryKey: ['milestones', workspaceId],
    queryFn: async () => {
      const response = await milestoneAPI.getByWorkspace(workspaceId);
      return response.data;
    },
  });

  const generatePitch = () => {
    if (!workspace || !analytics) return '';

    const completionRate = analytics.tasks.completionPercentage.toFixed(0);
    const teamSize = analytics.team?.length || 1;
    const milestonesAchieved = analytics.milestones.achieved;
    const totalMilestones = analytics.milestones.total;

    return `# ${workspace.name} - Investor Pitch

## Problem Statement
${workspace.description || 'We are solving a critical problem in the market that affects thousands of potential customers.'}

## Solution
Our platform provides an innovative solution that addresses this problem through:
- Streamlined execution and task management
- Data-driven decision making
- Collaborative team workflows
- Measurable progress tracking

## Traction & Metrics
- **Team Size:** ${teamSize} active member${teamSize > 1 ? 's' : ''}
- **Execution Rate:** ${completionRate}% task completion rate
- **Milestones:** ${milestonesAchieved} of ${totalMilestones} achieved
- **Active Tasks:** ${analytics.tasks.total} tasks in progress
- **Velocity:** Consistently delivering on sprint goals

## Market Opportunity
The market for startup operations and execution tools is growing rapidly, with early-stage founders seeking better ways to:
- Validate ideas quickly
- Manage execution efficiently
- Scale operations systematically
- Make data-driven decisions

## Business Model
We are building a sustainable business through:
- Subscription-based revenue model
- Tiered pricing for different team sizes
- Enterprise solutions for accelerators and incubators
- Premium features for advanced analytics

## Roadmap & Milestones
${milestones && milestones.length > 0 
  ? milestones.map((m: any) => `- **${m.title}** (Target: ${new Date(m.targetDate).toLocaleDateString()})`).join('\n')
  : '- Launch MVP\n- Acquire first 100 users\n- Achieve product-market fit\n- Scale to 1000+ users'
}

## Team
Our team brings together expertise in:
- Product development and execution
- Startup operations and scaling
- Data analytics and insights
- User experience and design

## Why Now?
- Remote work has accelerated the need for better collaboration tools
- Early-stage founders need more structured approaches to execution
- Data-driven decision making is becoming essential for startup success
- The market is ready for a unified operations platform

## The Ask
We are seeking investment to:
- Accelerate product development
- Expand our team
- Scale our go-to-market efforts
- Build strategic partnerships

## Contact
For more information or to schedule a detailed presentation, please reach out to our team.

---
*Generated by StartupOps AI - ${new Date().toLocaleDateString()}*
`;
  };

  const pitch = generatePitch();

  const handleCopy = () => {
    navigator.clipboard.writeText(pitch);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([pitch], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${workspace?.name || 'pitch'}-deck.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!workspace || !analytics) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-gray-600">Loading pitch data...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Card className="bg-gradient-to-r from-purple-50 to-blue-50 border-none">
        <div className="flex items-start gap-3">
          <Sparkles className="w-6 h-6 text-purple-600 mt-1" />
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">AI-Generated Pitch Deck</h3>
            <p className="text-sm text-gray-700 mb-4">
              We've automatically generated an investor pitch based on your workspace data, traction metrics, and milestones. 
              Customize it to match your unique story and vision.
            </p>
            <div className="flex gap-3">
              <Button onClick={handleCopy} variant="outline" size="sm">
                {copied ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 mr-2" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-2" />
                    Copy to Clipboard
                  </>
                )}
              </Button>
              <Button onClick={handleDownload} size="sm">
                <Download className="w-4 h-4 mr-2" />
                Download as Markdown
              </Button>
            </div>
          </div>
        </div>
      </Card>

      <Card>
        <div className="flex items-center gap-3 mb-4">
          <FileText className="w-6 h-6 text-blue-600" />
          <h3 className="text-lg font-semibold">Pitch Preview</h3>
        </div>
        <div className="prose prose-sm max-w-none">
          <pre className="whitespace-pre-wrap bg-gray-50 p-6 rounded-lg text-sm text-gray-800 font-mono overflow-x-auto">
            {pitch}
          </pre>
        </div>
      </Card>

      <Card className="bg-blue-50 border-none">
        <h4 className="font-semibold text-blue-900 mb-2">Next Steps</h4>
        <ul className="text-sm text-blue-800 space-y-1">
          <li>• Customize the pitch with your unique value proposition</li>
          <li>• Add specific market data and competitive analysis</li>
          <li>• Include financial projections and funding requirements</li>
          <li>• Create visual slides using tools like Pitch, Canva, or PowerPoint</li>
          <li>• Practice your delivery and get feedback from mentors</li>
        </ul>
      </Card>
    </div>
  );
}
